version: '3.8'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: perfa-otel-collector
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ../assets/otel/otel-collector-config.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
    depends_on:
      - jaeger
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: perfa-jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - QUERY_BASE_PATH=/api/monitor/jaeger
    ports:
      - "16686:16686"
      - "14268:14268"
      - "4317"
    restart: unless-stopped
